import { Injectable, Logger, NotFoundException, ForbiddenException, Inject } from '@nestjs/common';
import { Knex } from 'knex';
import { KNEX_CONNECTION } from '@/database/database.module';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  TableCell,
  TableRow,
  Table,
  WidthType,
  ShadingType,
} from 'docx';
import { v2 as cloudinary } from 'cloudinary';
import { ConfigService } from '@nestjs/config';
import PDFDocument from 'pdfkit';

export interface DocumentSection {
  heading: string;
  content: string;
}

export interface GenerateDocumentParams {
  userId: string;
  conversationId?: string;
  title: string;
  topic: string;
  sections: DocumentSection[];
  researchContext?: string;
  depth?: 'brief' | 'standard' | 'comprehensive';
  format?: 'docx' | 'pdf';
}

export interface GeneratedDocument {
  docId: string;
  downloadUrl: string;
}

@Injectable()
export class DocumentService {
  private readonly logger = new Logger(DocumentService.name);

  constructor(
    @Inject(KNEX_CONNECTION) private readonly knex: Knex,
    private readonly configService: ConfigService,
  ) {
    cloudinary.config({
      cloud_name: this.configService.get('cloudinary.cloudName'),
      api_key: this.configService.get('cloudinary.apiKey'),
      api_secret: this.configService.get('cloudinary.apiSecret'),
    });
  }

  // Maximum sections allowed per depth level (excluding the research references section).
  private readonly DEPTH_SECTION_LIMITS: Record<'brief' | 'standard' | 'comprehensive', number> = {
    brief: 4,
    standard: 7,
    comprehensive: 12,
  };

  async generateAndUpload(params: GenerateDocumentParams): Promise<GeneratedDocument> {
    const { userId, conversationId, title, topic, sections, researchContext, depth = 'standard', format = 'docx' } = params;

    this.logger.log(`Generating document: "${title}" for user ${userId} (depth: ${depth}, format: ${format})`);

    // Trim sections to the depth limit before enrichment.
    const sectionLimit = this.DEPTH_SECTION_LIMITS[depth];
    const trimmedSections = sections.slice(0, sectionLimit);

    const enrichedSections = researchContext
      ? this.enrichSectionsWithResearch(trimmedSections, researchContext)
      : trimmedSections;

    const buffer = format === 'pdf'
      ? await this.buildPdf(title, enrichedSections)
      : await this.buildDocx(title, enrichedSections);

    const downloadUrl = await this.uploadToCloudinary(buffer, title, format);

    const [row] = await this.knex('generated_documents')
      .insert({
        user_id: userId,
        conversation_id: conversationId ?? null,
        title,
        topic: topic || null,
        download_url: downloadUrl,
        section_count: enrichedSections.length,
        depth,
        format,
      })
      .returning('id');

    const docId = typeof row === 'object' ? (row as Record<string, string>).id : String(row);
    this.logger.log(`Document saved: id=${docId}, url=${downloadUrl}`);

    return { docId, downloadUrl };
  }

  private enrichSectionsWithResearch(
    sections: DocumentSection[],
    researchContext: string,
  ): DocumentSection[] {
    if (!researchContext.trim()) return sections;

    // Append research as a final "References & Further Reading" section
    const refSection: DocumentSection = {
      heading: 'References & Further Reading',
      content: researchContext
        .split('\n\n')
        .filter((block) => block.trim())
        .slice(0, 5)
        .map((block) => {
          const lines = block.split('\n').filter(Boolean);
          return lines[0] ?? block;
        })
        .join('\n'),
    };

    return [...sections, refSection];
  }

  private async buildDocx(title: string, sections: DocumentSection[]): Promise<Buffer> {
    const children: Paragraph[] = [
      // Document title
      new Paragraph({
        children: [
          new TextRun({
            text: title,
            bold: true,
            size: 48,
            color: '1a1a2e',
          }),
        ],
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      }),

      // Generated by line
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated by CognIX AI  •  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
            italics: true,
            size: 20,
            color: '666666',
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 800 },
      }),

      // Horizontal rule (empty paragraph with border)
      new Paragraph({
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 6, color: '4a90d9' },
        },
        spacing: { after: 600 },
        children: [],
      }),
    ];

    // Add each section
    for (const section of sections) {
      // Section heading
      children.push(
        new Paragraph({
          text: section.heading,
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }),
      );

      // Section content — handle bullet points (lines starting with - or •)
      const lines = section.content.split('\n').filter((l) => l.trim());

      for (const line of lines) {
        const trimmed = line.trim();
        const isBullet = trimmed.startsWith('- ') || trimmed.startsWith('• ') || trimmed.startsWith('* ');

        if (isBullet) {
          const bulletText = trimmed.replace(/^[-•*]\s+/, '');
          children.push(
            new Paragraph({
              children: [new TextRun({ text: bulletText, size: 22 })],
              bullet: { level: 0 },
              spacing: { after: 80 },
            }),
          );
        } else if (trimmed) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: trimmed, size: 22 })],
              spacing: { after: 160 },
            }),
          );
        }
      }
    }

    // Footer paragraph
    children.push(
      new Paragraph({
        border: {
          top: { style: BorderStyle.SINGLE, size: 6, color: 'cccccc' },
        },
        spacing: { before: 800 },
        children: [
          new TextRun({
            text: 'This document was generated by CognIX AI using real-time research and AI analysis.',
            italics: true,
            size: 18,
            color: '999999',
          }),
        ],
      }),
    );

    const doc = new Document({
      styles: {
        default: {
          document: {
            run: { font: 'Calibri', size: 22 },
          },
        },
      },
      sections: [
        {
          properties: {
            page: {
              margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
            },
          },
          children,
        },
      ],
    });

    return Packer.toBuffer(doc);
  }

  private buildPdf(title: string, sections: DocumentSection[]): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 72, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const blue = '#2563eb';
      const darkBlue = '#1a1a2e';
      const grey = '#666666';

      // Title page header
      doc.rect(0, 0, doc.page.width, 120).fill(darkBlue);
      doc.fillColor('white').fontSize(26).font('Helvetica-Bold').text(title, 72, 40, { width: doc.page.width - 144, align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(11).font('Helvetica').fillColor('#a0aec0').text(
        `Generated by CognIX AI  •  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        { align: 'center' },
      );

      doc.moveDown(2);

      // Sections
      for (const section of sections) {
        // Section heading
        doc.fillColor(blue).fontSize(14).font('Helvetica-Bold').text(section.heading);
        doc.moveDown(0.3);
        doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor(blue).lineWidth(1).stroke();
        doc.moveDown(0.5);

        // Section content
        const lines = section.content.split('\n').filter((l) => l.trim());
        for (const line of lines) {
          const trimmed = line.trim();
          const isBullet = trimmed.startsWith('- ') || trimmed.startsWith('• ') || trimmed.startsWith('* ');
          if (isBullet) {
            const bulletText = trimmed.replace(/^[-•*]\s+/, '');
            doc.fillColor('#333').fontSize(11).font('Helvetica')
              .text(`• ${bulletText}`, { indent: 16, paragraphGap: 4 });
          } else if (trimmed) {
            doc.fillColor('#333').fontSize(11).font('Helvetica').text(trimmed, { paragraphGap: 6 });
          }
        }
        doc.moveDown(1);
      }

      // Footer
      doc.moveDown(1);
      doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor('#cccccc').lineWidth(0.5).stroke();
      doc.moveDown(0.5);
      doc.fillColor(grey).fontSize(9).font('Helvetica-Oblique').text(
        'This document was generated by CognIX AI using real-time research and AI analysis.',
        { align: 'center' },
      );

      doc.end();
    });
  }

  private uploadToCloudinary(buffer: Buffer, title: string, format: 'docx' | 'pdf' = 'docx'): Promise<string> {
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60);

    const publicId = `cognix/documents/${Date.now()}-${slug}`;

    return new Promise((resolve, reject) => {
      const stream = cloudinary.uploader.upload_stream(
        {
          resource_type: 'raw',
          public_id: publicId,
          format,
        },
        (error, result) => {
          if (error) {
            this.logger.error('Cloudinary document upload error:', error.message);
            reject(new Error(`Document upload failed: ${error.message}`));
            return;
          }
          if (!result) {
            reject(new Error('No result from Cloudinary'));
            return;
          }
          this.logger.log(`Document uploaded: ${result.secure_url}`);
          resolve(result.secure_url);
        },
      );

      stream.on('error', (err) => reject(new Error(`Upload stream error: ${err.message}`)));
      stream.end(buffer);
    });
  }

  async getUserDocuments(
    userId: string,
    page = 1,
    limit = 20,
    search?: string,
  ): Promise<{ items: Record<string, unknown>[]; total: number; page: number; limit: number }> {
    const offset = (page - 1) * limit;

    const applySearch = (qb: Knex.QueryBuilder) => {
      qb.where({ user_id: userId });
      if (search?.trim()) {
        const pattern = `%${search.trim()}%`;
        qb.andWhere((sub) =>
          sub.where('title', 'ilike', pattern).orWhere('topic', 'ilike', pattern),
        );
      }
    };

    const [countResult, items] = await Promise.all([
      this.knex('generated_documents')
        .where((qb) => applySearch(qb))
        .count('id as total')
        .first() as unknown as Promise<{ total: string | number }>,
      this.knex('generated_documents')
        .where((qb) => applySearch(qb))
        .orderBy('created_at', 'desc')
        .limit(limit)
        .offset(offset)
        .select('id', 'title', 'topic', 'download_url', 'section_count', 'depth', 'created_at'),
    ]);

    return {
      items,
      total: Number(countResult?.total ?? 0),
      page,
      limit,
    };
  }

  async getDocumentById(docId: string, userId: string): Promise<Record<string, unknown>> {
    const doc = await this.knex('generated_documents')
      .where({ id: docId, user_id: userId })
      .first();

    if (!doc) throw new NotFoundException('Document not found');
    return doc;
  }

  async deleteDocument(docId: string, userId: string): Promise<void> {
    const doc = await this.knex('generated_documents').where({ id: docId }).first();
    if (!doc) throw new NotFoundException('Document not found');
    if (doc.user_id !== userId) throw new ForbiddenException('Access denied');

    // Cloudinary cleanup — best-effort; don't block the delete on failure.
    if (doc.cloudinary_public_id) {
      cloudinary.uploader
        .destroy(doc.cloudinary_public_id, { resource_type: 'raw' })
        .catch((err) => this.logger.warn(`Cloudinary delete failed for ${doc.cloudinary_public_id}:`, err));
    }

    await this.knex('generated_documents').where({ id: docId }).delete();
    this.logger.log(`Document deleted: id=${docId} by user=${userId}`);
  }
}
