import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('guest_sessions', (table) => {
    // UUID generated by the frontend and stored in localStorage
    table.uuid('id').primary();
    // How many prompts this guest has used (voice + text combined)
    table.integer('prompt_count').notNullable().defaultTo(0);
    // Max prompts allowed before forcing sign-up
    table.integer('prompt_limit').notNullable().defaultTo(5);
    table.timestamp('created_at').defaultTo(knex.fn.now());
    table.timestamp('last_used_at').defaultTo(knex.fn.now());
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('guest_sessions');
}
