import { Injectable, Inject, Logger } from '@nestjs/common';
import { Knex } from 'knex';
import { KNEX_CONNECTION } from '@/database/database.module';

export interface GuestSession {
  id: string;
  prompt_count: number;
  prompt_limit: number;
  created_at: Date;
  last_used_at: Date;
}

@Injectable()
export class GuestSessionService {
  private readonly logger = new Logger(GuestSessionService.name);
  readonly PROMPT_LIMIT = 5;

  constructor(@Inject(KNEX_CONNECTION) private readonly knex: Knex) {}

  /**
   * Find an existing guest session or create a new one.
   * The id is a UUID generated by the client and stored in localStorage.
   */
  async findOrCreate(guestSessionId: string): Promise<GuestSession> {
    const existing = await this.knex('guest_sessions')
      .where('id', guestSessionId)
      .first();

    if (existing) return existing;

    const [created] = await this.knex('guest_sessions')
      .insert({ id: guestSessionId, prompt_limit: this.PROMPT_LIMIT })
      .returning('*');

    return created;
  }

  /**
   * Returns true if the guest is still within their prompt limit.
   */
  async canSendPrompt(guestSessionId: string): Promise<boolean> {
    const session = await this.findOrCreate(guestSessionId);
    return session.prompt_count < session.prompt_limit;
  }

  /**
   * Atomically increment the prompt count and return the updated session.
   */
  async incrementPromptCount(guestSessionId: string): Promise<GuestSession> {
    const [updated] = await this.knex('guest_sessions')
      .where('id', guestSessionId)
      .update({ prompt_count: this.knex.raw('prompt_count + 1'), last_used_at: new Date() })
      .returning('*');

    return updated;
  }

  /**
   * Returns { used, limit, remaining } for the guest session.
   */
  async getPromptStatus(guestSessionId: string): Promise<{ used: number; limit: number; remaining: number }> {
    const session = await this.findOrCreate(guestSessionId);
    return {
      used: session.prompt_count,
      limit: session.prompt_limit,
      remaining: Math.max(0, session.prompt_limit - session.prompt_count),
    };
  }
}
